### PR TITLE
cleanup: remove broken websocket connection

### LINKED ISSUE #35: App stops responding
After opening and closing the wallet a few times the service stops responding and no further interaction is possible (api stops responding).
This happens rather quickly and can be reproduced on my side after locking/unlocking the wallet four to five times.

In this state, when reloading the page, the app stops rendering completely.

Server logs do not give a strong hint about what might be wrong.
```sh
> root@edd0ae308a67:~/.joinmarket/logs# tail -f jmwalletd_stdout.log -n 200
```
```
<Request at 0x7f7e2d385b80 method=POST uri=/api/v1/wallet/t.jmdat/unlock clientproto=HTTP/1.1> [...]
2022-02-01 10:49:37,349 [DEBUG]  rpc: listaddressgroupings []
2022-02-01 10:49:37,353 [INFO]  Detected new wallet, performing initial import
2022-02-01 10:49:37,353 [DEBUG]  requesting detailed wallet history
2022-02-01 10:49:38,254 [DEBUG]  rpc: listlabels []
2022-02-01 10:49:38,255 [DEBUG]  rpc: getaddressesbylabel ['joinmarket-wallet-d4ef50']
2022-02-01 10:49:38,273 [DEBUG]  got used indices: {0: [0, 0, 0, 0], 1: [0, 0, 0, 0], 2: [0, 0, 0, 0], 3: [0, 0, 0, 0], 4: [0, 0, 0, 0]}
2022-02-01 10:49:38,352 [DEBUG]  rpc: listlabels []
2022-02-01 10:49:38,354 [DEBUG]  rpc: getaddressesbylabel ['joinmarket-wallet-d4ef50']
2022-02-01 10:49:38,362 [DEBUG]  Wallet successfully synced
2022-02-01 10:49:38,363 [DEBUG]  rpc: listunspent []
2022-02-01 10:49:38,371 [DEBUG]  bitcoind sync_unspent took 0.008394718170166016sec
2022-02-01 10:49:38,382 [INFO]  Starting transaction monitor in walletservice
<Request at 0x7f7e2d3f6c40 method=GET uri=/api/v1/wallet/t.jmdat/display clientproto=HTTP/1.1> [...]
<Request at 0x7f7e2d3f6df0 method=GET uri=/api/v1/wallet/t.jmdat/lock clientproto=HTTP/1.1> [...]
<Request at 0x7f7e2d396a00 method=POST uri=/api/v1/wallet/t.jmdat/unlock clientproto=HTTP/1.1> [...]
2022-02-01 10:49:44,289 [DEBUG]  rpc: listaddressgroupings []
2022-02-01 10:49:44,292 [INFO]  Detected new wallet, performing initial import
2022-02-01 10:49:44,292 [DEBUG]  requesting detailed wallet history
2022-02-01 10:49:45,208 [DEBUG]  rpc: listlabels []
2022-02-01 10:49:45,219 [DEBUG]  rpc: getaddressesbylabel ['joinmarket-wallet-d4ef50']
2022-02-01 10:49:45,239 [DEBUG]  got used indices: {0: [0, 0, 0, 0], 1: [0, 0, 0, 0], 2: [0, 0, 0, 0], 3: [0, 0, 0, 0], 4: [0, 0, 0, 0]}
2022-02-01 10:49:45,309 [DEBUG]  rpc: listlabels []
2022-02-01 10:49:45,311 [DEBUG]  rpc: getaddressesbylabel ['joinmarket-wallet-d4ef50']
2022-02-01 10:49:45,318 [DEBUG]  Wallet successfully synced
2022-02-01 10:49:45,319 [DEBUG]  rpc: listunspent []
2022-02-01 10:49:45,326 [DEBUG]  bitcoind sync_unspent took 0.00782322883605957sec
2022-02-01 10:49:45,342 [INFO]  Starting transaction monitor in walletservice
```

~~Maybe `Starting transaction monitor in walletservice` causes problems on the server, but this is just unfounded speculation.
Seems like there cannot be much done on the client side, except for better handling of the unresponsiveness of the server maybe.~~

### PR DESCRIPTION
**Pull request by theborakompanioni**
Fixes #35 . Thanks for finding @dnlggr.

### CODE REVIEW

**Comment by dennisreimann** [comment]
This shouldn't be removed but fixed. I haven't figured out yet whether it is a problem in the web server/proxy or in the API's web socket which makes it fail. However, making this web socket connection work would be great.

**Comment by theborakompanioni** [comment]
> This shouldn't be removed but fixed. 

Hm.. I know what you mean. However, it does not do anything yet while slowing down development.
Would re-adding it in a feature branch + some functionality makes sense in the meantime?

**Comment by dennisreimann** [comment]
Good idea!

**Review by dergigi — APPROVED** [review]
Sounds like a plan! I'll merge this now to get it out of the way in `master`.

**Pull request merged**
