### PR TITLE
feat(scheduler): invert external/internal toggle

### PR DESCRIPTION
**Pull request by dergigi**
This PR inverts the external address toggle and adjusts the behavior of the scheduler to "internal" by default.

Also adjusts and updates copy, fixing #248

Screenshot 2022-05-11 at 15 11 07

Screenshot 2022-05-11 at 15 11 18

### CODE REVIEW

**Review by dnlggr — CHANGES_REQUESTED** [review]
That's a good change! Much clearer than  before. 👏 👍 

One issue though: When the screen initially loads, the internal destination addresses won't be set and the button "Start" button will be disabled. That's because the internal addresses will only be set once the toggle [is actively un-toggled](https://github.com/joinmarket-webui/joinmarket-webui/pull/257/files#diff-5aa1ef24bb3d55e6829234b19485cd23b10ff61aa8ac49179828246df4857c00R262). Only after toggling the button back and forth will the internal addresses be set and the button be activated. 

With the new logic, we'll need to provide internal destination addresses as default values for the address fields.

https://user-images.githubusercontent.com/10026790/168023614-759bc5e7-70b3-4cb7-9edb-52fd9403dd91.mov

**Comment by dnlggr** [comment]
Pushed a fix that should work (I hope). TL;DR: Waits with rendering the form unil the wallet is loaded. Once the wallet is loaded, [sets the form's initial values](https://github.com/joinmarket-webui/joinmarket-webui/pull/257/commits/e2f1d59c6712c5548f015314dcb12f07e1c4f499#diff-5aa1ef24bb3d55e6829234b19485cd23b10ff61aa8ac49179828246df4857c00R209-R212) to 3 internal addresses.

@theborakompanioni Can you have a quick look please? 🙏  Don't want to approve my own code. 😅

**Comment by dergigi** [comment]
> When the screen initially loads, the internal destination addresses won't be set

Ah, damn. Thanks for catching and fixing that! 🙏

**Review by theborakompanioni — APPROVED** [review]
lgtm :+1:

**Pull request merged**
