### PR TITLE
docs: add automated changelog generation

### PR DESCRIPTION
**Pull request by dnlggr**
🚨  I don't have much experience releasing JavaScript/npm stuff so I might be missing some best practices here.

---

Adds npm scripts to generate a changelog template after bumping the version:

- `npm run changelog`

This does:
- Prefill the changelog with the changes from the current version down to the last version (based on the current version in `package.json`).

We can then manually edit the changelog, commit and PR it. 

We then still need to manually tag the release on master after merging the "prepare" PR. Depending on how our release process evolves we can of course also automate these steps in the future even more. For example it would be nice to automatically tag a release and create a GitHub release (based on the changelog) using GitHub actions.

## Changelog

We already started using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) for our commit messages when we squash a PR. That make sit easy to prefill the changelog with these messages to get something that's already human readable and adheres to the [keep-a-changelog](https://keepachangelog.com/en/1.0.0/) format.

I've set it up so that all commits of types `feat`, `update`, `remove`, `fix`, `security` get included in the changelog by default. This is just what came to my mind based on [keep-a-changelog](https://keepachangelog.com/en/1.0.0/). Let me know if we should include/remove things.

I left the changelog uncommited on purpose so that we can manually go over it and adapt it as needed (remove/add things, reformulate, etc.)

## Example

The following is how the automatically generated changelog for v0.0.3 would look like. Not perfect but with a few manual edits and deletions I think it'll be quite nice—and thanks to the auto-generation much much less work than collecting and linking all that info manually.

#### Added

* adapt favicon color based on system theme ([#39](https://github.com/joinmarket-webui/joinmarket-webui/issues/39)) ([5f1d6e9](https://github.com/joinmarket-webui/joinmarket-webui/commit/5f1d6e97f8f336f458303b57fddce4f27d0abe0c))
* add connection indicator to footer ([#55](https://github.com/joinmarket-webui/joinmarket-webui/issues/55)) ([6470ab4](https://github.com/joinmarket-webui/joinmarket-webui/commit/6470ab431627c091a40016b9baa2516157ca5ba2))
* add privacy levels ([#51](https://github.com/joinmarket-webui/joinmarket-webui/issues/51)) ([7546ca7](https://github.com/joinmarket-webui/joinmarket-webui/commit/7546ca74d44369c4d8dba6961b4d441bd98edb09))
* add sat symbol & update balance UI ([#11](https://github.com/joinmarket-webui/joinmarket-webui/issues/11)) ([4351d13](https://github.com/joinmarket-webui/joinmarket-webui/commit/4351d1380e3a3d7ba872dce1f2281d192ad095ec))
* add settings screen ([#26](https://github.com/joinmarket-webui/joinmarket-webui/issues/26)) ([867fff3](https://github.com/joinmarket-webui/joinmarket-webui/commit/867fff330bac37c4c741ca528e7f9ffa0511d2fd))
* add theming support ([#10](https://github.com/joinmarket-webui/joinmarket-webui/issues/10)) ([d7268aa](https://github.com/joinmarket-webui/joinmarket-webui/commit/d7268aa70c54fa08a094b0e4c1e8eb2c88e00c77))
* developer docs ([#37](https://github.com/joinmarket-webui/joinmarket-webui/issues/37)) ([d843770](https://github.com/joinmarket-webui/joinmarket-webui/commit/d84377071a87c2011b5fe1bc957243f491f66cfd))
* display basic yield generator report ([#73](https://github.com/joinmarket-webui/joinmarket-webui/issues/73)) ([b37de70](https://github.com/joinmarket-webui/joinmarket-webui/commit/b37de7083ecb9575d798a2df2aa69a6d21dba0a0))
* do not autocomplete password when creating wallet ([#38](https://github.com/joinmarket-webui/joinmarket-webui/issues/38)) ([0db76d9](https://github.com/joinmarket-webui/joinmarket-webui/commit/0db76d99ddffb6ba451ff98601660ffa173a0110))
* fancy toggle switch ([#63](https://github.com/joinmarket-webui/joinmarket-webui/issues/63)) ([ed8aa4b](https://github.com/joinmarket-webui/joinmarket-webui/commit/ed8aa4b22b2dcbcbefa34fce6ccc81aaaec9c190))
* hide sensitive info on wallet create ([#77](https://github.com/joinmarket-webui/joinmarket-webui/issues/77)) ([174726b](https://github.com/joinmarket-webui/joinmarket-webui/commit/174726b74fd889980c124b9d56e2c1d1766e8a2f))
* improve wording in settings ([#71](https://github.com/joinmarket-webui/joinmarket-webui/issues/71)) ([cd2f0bf](https://github.com/joinmarket-webui/joinmarket-webui/commit/cd2f0bf98be474d60be0e142a1a7e89d55f37e44))
* rename accounts to privacy levels ([#79](https://github.com/joinmarket-webui/joinmarket-webui/issues/79)) ([3b882f4](https://github.com/joinmarket-webui/joinmarket-webui/commit/3b882f4da8aeb912471eaf4e7bf2431b9b89f308))
* setup code formatting ([#21](https://github.com/joinmarket-webui/joinmarket-webui/issues/21)) ([08232d7](https://github.com/joinmarket-webui/joinmarket-webui/commit/08232d7d365f279e7632016120eab53f57ecff90))
* style navbar ([#29](https://github.com/joinmarket-webui/joinmarket-webui/issues/29)) ([699e951](https://github.com/joinmarket-webui/joinmarket-webui/commit/699e951fda7f7311cd7a49ad97925731e99e5395))
* update create wallet flow ([#62](https://github.com/joinmarket-webui/joinmarket-webui/issues/62)) ([8ed27ae](https://github.com/joinmarket-webui/joinmarket-webui/commit/8ed27ae745f46ffda246006b5f7ba549493aa39b))
* update earn page ([#82](https://github.com/joinmarket-webui/joinmarket-webui/issues/82)) ([7d62a38](https://github.com/joinmarket-webui/joinmarket-webui/commit/7d62a3820a83103a691633c8030bc26312e8310d))
* update receive page ([#85](https://github.com/joinmarket-webui/joinmarket-webui/issues/85)) ([756d8e8](https://github.com/joinmarket-webui/joinmarket-webui/commit/756d8e8a93185933d0a92713f92bf92f7ccdf664))
* update send page ([#76](https://github.com/joinmarket-webui/joinmarket-webui/issues/76)) ([0d71915](https://github.com/joinmarket-webui/joinmarket-webui/commit/0d71915180dafb03ce69c8ba82c3c76fa5b2db46))
* update wallets page ([#64](https://github.com/joinmarket-webui/joinmarket-webui/issues/64)) ([f900344](https://github.com/joinmarket-webui/joinmarket-webui/commit/f90034454920fb77ddb7fedcbe3e92f1bb994322))

#### Fixed

* add integration pr links to readme ([#95](https://github.com/joinmarket-webui/joinmarket-webui/issues/95)) ([20aa39b](https://github.com/joinmarket-webui/joinmarket-webui/commit/20aa39bce28f20e3ad70527b28b04468d6ee1daf))
* brighten loading indicator in dark theme ([#53](https://github.com/joinmarket-webui/joinmarket-webui/issues/53)) ([693fdf1](https://github.com/joinmarket-webui/joinmarket-webui/commit/693fdf123f3c080fa347603d00f8758e787b65e7))
* change navbar collapse to offcanvas ([#44](https://github.com/joinmarket-webui/joinmarket-webui/issues/44)) ([97ae86b](https://github.com/joinmarket-webui/joinmarket-webui/commit/97ae86b7a1f93f161b9ab38a741cdd473c7adf4b))
* condition check during wallet confirmation ([#93](https://github.com/joinmarket-webui/joinmarket-webui/issues/93)) ([9d0baf1](https://github.com/joinmarket-webui/joinmarket-webui/commit/9d0baf1173b1cecc521522d08bc5983bfcfb5200))
* display amount of addresses correctly ([#49](https://github.com/joinmarket-webui/joinmarket-webui/issues/49)) ([216dc2b](https://github.com/joinmarket-webui/joinmarket-webui/commit/216dc2b033daeb57756d8062d02e946cfe4cbd4c))
* display info text on send page if service is running ([#86](https://github.com/joinmarket-webui/joinmarket-webui/issues/86)) ([4070d70](https://github.com/joinmarket-webui/joinmarket-webui/commit/4070d7026c0ba7eac7fca02a3c14c65da510f67b))
* extract error message of text/html response ([#84](https://github.com/joinmarket-webui/joinmarket-webui/issues/84)) ([ffa1afa](https://github.com/joinmarket-webui/joinmarket-webui/commit/ffa1afa31aa311cb6efe2838316ca6850fe77713))
* fix and dry up font featues ([#98](https://github.com/joinmarket-webui/joinmarket-webui/issues/98)) ([ac762c5](https://github.com/joinmarket-webui/joinmarket-webui/commit/ac762c520486e33fc493b3de59ad8b02f6aa5332))
* hidden balance icon alignment and size ([#52](https://github.com/joinmarket-webui/joinmarket-webui/issues/52)) ([8bb8b7b](https://github.com/joinmarket-webui/joinmarket-webui/commit/8bb8b7b98f6f55855ffed4487cd8a0aba1068e06))
* initialize local storage with default values ([#33](https://github.com/joinmarket-webui/joinmarket-webui/issues/33)) ([712b289](https://github.com/joinmarket-webui/joinmarket-webui/commit/712b289ddce94a385529e1cc3f4dd2416f65cbc4))
* Invalid DOM property 'class' in App ([d2173cd](https://github.com/joinmarket-webui/joinmarket-webui/commit/d2173cdb89793b4da4561e3fd374413158dce7ff))
* navbar padding ([#48](https://github.com/joinmarket-webui/joinmarket-webui/issues/48)) ([1a04910](https://github.com/joinmarket-webui/joinmarket-webui/commit/1a04910f61b0d5b2251065cb754e7f89dae52728))
* navigate to root on unmapped path ([#89](https://github.com/joinmarket-webui/joinmarket-webui/issues/89)) ([6f0f515](https://github.com/joinmarket-webui/joinmarket-webui/commit/6f0f515e87c177c8e5bf71009782497f779eac83))
* prevent dom validation warning ([#5](https://github.com/joinmarket-webui/joinmarket-webui/issues/5)) ([88e2ed6](https://github.com/joinmarket-webui/joinmarket-webui/commit/88e2ed66b766662cc3c79f938396c83d2d2a190c))
* show loading indicator until all data is fetched ([#3](https://github.com/joinmarket-webui/joinmarket-webui/issues/3)) ([37d882f](https://github.com/joinmarket-webui/joinmarket-webui/commit/37d882f9fb61faff2b476f63f92610fefd220473))
* update sat symbol ([#36](https://github.com/joinmarket-webui/joinmarket-webui/issues/36)) ([765c9d7](https://github.com/joinmarket-webui/joinmarket-webui/commit/765c9d7315f96843cefeddbe51b49682f652ea2a))
* use sprite instead of plain logo ([215e2fa](https://github.com/joinmarket-webui/joinmarket-webui/commit/215e2fa9a68ad7bef79a80330a45b903d485f160))

### CODE REVIEW

**Comment by dennisreimann** [comment]
Looks good from first glance. Just fyi there is also the `npm version` command that includes the tagging.

**Comment by dnlggr** [comment]
> Just fyi there is also the npm version command that includes the tagging.

Nice, thanks! I think I'd even prefer that. The library I use for the changelog wants to bump the version by itself but I'd much rather stay as close to native npm tooling as possible. I'll check if I can integrate `npm version` somehow and let the changelog library only generate the changelog and nothing else.

**Comment by dnlggr** [comment]
Updated it to `npm run changelog`. Doesn't bumpt the version now. It now takes the version from `package.json` and updates the changelog with all changes between that version and the last tag. That way we can keep using npm tooling for bumping etc.

**Review by theborakompanioni — APPROVED** [review]
Nice! :muscle: 

Only nit: `package-lock.json` has been checked in with v0.0.3 - causing untracked git changes on `npm install`.

**Review by dergigi — APPROVED** [review]
Great stuff! Looks good to me ✅ 

I tested it by bumping the version to 0.0.3, everything worked as expected. I'd say let's merge this and update the changelog in one go for all past versions once we do the release tag? 

One more thing that just came to mind: any thoughts on `rc` tags for release candidates? Not that it's required now, just wondering if some of you have any strong opinions or insights in that regard.

**Comment by dnlggr** [comment]
> Only nit: package-lock.json has been checked in with v0.0.3 - causing untracked git changes on npm install.

Fixed! That was from testing and I probably forgot to revert it.

**Comment by dnlggr** [comment]
> One more thing that just came to mind: any thoughts on rc tags for release candidates? Not that it's required now, just wondering if some of you have any strong opinions or insights in that regard.

No strong opinions. We could also think about adding a [`-alpha`](https://semver.org/#spec-item-9) or something like this now that I think about it.

**Comment by dnlggr** [comment]
> update the changelog in one go for all past versions

We'll need to do that manually since we didn't use conventional commits back then—so not much will show up in the autogenerated changelog. I can take care of that in a separate PR though.

As for the general release process, since master is a protected branch, we won't be able to bump and tag in one go (assuming we want the release tag on master which probably makes sense I would say). We'd have to do somethign like this:

1. Prepare release: Bump and update changelog.
2. PR changes to master
3. Tag release on master

Thoughts? If ok with everyone I can add npm scripts for that to make the process easier and documented in a way.

**Comment by dnlggr** [comment]
> > update the changelog in one go for all past versions
> 
> We'll need to do that manually since we didn't use conventional commits back then—so not much will show up in the autogenerated changelog. I can take care of that in a separate PR though.
> 
> As for the general release process, since master is a protected branch, we won't be able to bump and tag in one go (assuming we want the release tag on master which probably makes sense I would say). We'd have to do somethign like this:
> 
>     1. Prepare release: Bump and update changelog.
> 
>     2. PR changes to master
> 
>     3. Tag release on master
> 
> 
> Thoughts? If ok with everyone I can add npm scripts for that to make the process easier and documented in a way.

Moving this discussion to an issue. ☝️ https://github.com/joinmarket-webui/joinmarket-webui/issues/105

**Pull request merged**
