### PR TITLE
chore: pre-alpha -> beta

### PR DESCRIPTION
**Pull request by dergigi**
Beta soon! (tm)

### CODE REVIEW

**Comment by dnlggr** [comment]
We're already on _alpha_. (See [here](https://github.com/joinmarket-webui/joinmarket-webui/blob/master/src/i18n/locales/en/translation.json#L17) for the current translation string). The hardcoded string here is just an artifact that the translation library needs. Its content's don't matter though. You can read about it [here](https://react.i18next.com/latest/trans-component) but I don't recommend it, its super confusing and annoying.

**Comment by dnlggr** [comment]
Should we go straight to beta though? 😄

**Comment by dergigi** [comment]
God damnit 😅

**Comment by dergigi** [comment]
Let's rip out the i18n stuff for now and move straight to beta?

**Comment by dnlggr** [comment]
No need for ripping, you can just update the translations string here: https://github.com/joinmarket-webui/joinmarket-webui/blob/master/src/i18n/locales/en/translation.json#L17

**Comment by dergigi** [comment]
Should be good now, I think.

**Review by dnlggr — APPROVED** [review]
LGTM

**Pull request merged**
