### PR TITLE
WIP: feat: display spendable amount on Send page

### PR DESCRIPTION
**Pull request by theborakompanioni**
Display spendable amount on the Send page.

Gotchas:
- Some utxos can be auto-frozen by jm. These are not spendable and cannot be "unfrozen" via the api at the moment.
  How should this be displayed to the user?

Still todo:
- reload available balances after payment

### CODE REVIEW

**Comment by dergigi** [comment]
I'll review and test this PR as soon as the conflict is resolved.

**Comment by theborakompanioni** [comment]
> I'll review and test this PR as soon as the conflict is resolved.

I am not happy with the approach here.

The thing is.. should we even try to determine the "spendable" amount in the ui?
It'd be good to get this value from the server, as any changes in the mechanism would make our calculations obsolete, maybe plain wrong.

**Comment by dergigi** [comment]
> It'd be good to get this value from the server, as any changes in the mechanism would make our calculations obsolete, maybe plain wrong.

Agree, let's not do it client-side.

**Comment by dnlggr** [comment]
> It'd be good to get this value from the server, as any changes in the mechanism would make our calculations obsolete, maybe plain wrong.

Yeah that probably make sense! I'm closing this PR then, feel free to reopen if needed.

**Pull request closed without merging**
