### PR TITLE
ui: evenly spacing between jars in select modal

### PR DESCRIPTION
**Pull request by theborakompanioni**
Add more spacing to the jar selector modal.

Approve: Yes, looks better.
Decline: Let's keep it how it is.

### CODE REVIEW

**Comment by editwentyone** [comment]
better

**Comment by dnlggr** [comment]
How did you get to this state where some jars' balances are hidden and others' are not? Those balances aren't clickable are they?

**Comment by theborakompanioni** [comment]
> How did you get to this state where some jars' balances are hidden and others' are not? Those balances aren't clickable are they?

They are! Introduced in https://github.com/joinmarket-webui/joinmarket-webui/pull/247

**Comment by dnlggr** [comment]
Oh you're right! I feel like we should give the balance a minimum width then. Should take up the same space than the shortest balance possible (`0.00 000 000`). That way we'd get less UI issue with jars being super narrow.

**Comment by dnlggr** [comment]
Just tried out clicking the balances. It only works when you start out in "balance hidden" mode. 🤔 That's why I couldn't get it to work at first.

**Comment by theborakompanioni** [comment]
> Oh you're right! I feel like we should give the balance a minimum width then. Should take up the same space than the shortest balance possible (`0.00 000 000`). That way we'd get less UI issue with jars being super narrow.

Addressed in https://github.com/joinmarket-webui/joinmarket-webui/pull/360. Let me know what you think.

**Pull request closed without merging**
